//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CesiZen.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CesiZen.Domain.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect Email or password..
        /// </summary>
        internal static string CLIENT_AUTHENTICATION_FAILED {
            get {
                return ResourceManager.GetString("CLIENT_AUTHENTICATION_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect Email or password provided..
        /// </summary>
        internal static string CLIENT_AUTHENTICATION_MISMATCH {
            get {
                return ResourceManager.GetString("CLIENT_AUTHENTICATION_MISMATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete {0}.
        /// </summary>
        internal static string CLIENT_DELETION_FAILED {
            get {
                return ResourceManager.GetString("CLIENT_DELETION_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email failed to be verified..
        /// </summary>
        internal static string CLIENT_EMAIL_VERIFICATION_FAILED {
            get {
                return ResourceManager.GetString("CLIENT_EMAIL_VERIFICATION_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create {0}.
        /// </summary>
        internal static string CLIENT_INSERTION_FAILED {
            get {
                return ResourceManager.GetString("CLIENT_INSERTION_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have reached the maximum attempts! Your account is locked for 5 minutes..
        /// </summary>
        internal static string CLIENT_LOGINATTEMPS {
            get {
                return ResourceManager.GetString("CLIENT_LOGINATTEMPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account is locked for {0} minutes..
        /// </summary>
        internal static string CLIENT_LOGINATTEMPS_LOCKTIME {
            get {
                return ResourceManager.GetString("CLIENT_LOGINATTEMPS_LOCKTIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided {0} already exist..
        /// </summary>
        internal static string CLIENT_UNICITY_CONSTRAINT {
            get {
                return ResourceManager.GetString("CLIENT_UNICITY_CONSTRAINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update {0}.
        /// </summary>
        internal static string CLIENT_UPDATE_FAILED {
            get {
                return ResourceManager.GetString("CLIENT_UPDATE_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update {0}.
        /// </summary>
        internal static string CLIENT_UPDATE_PROPERTY_FAILED {
            get {
                return ResourceManager.GetString("CLIENT_UPDATE_PROPERTY_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current {0} already exist in the Database. [info : {1}].
        /// </summary>
        internal static string LOG_CHECK_UNICITY_CONSTRAINT {
            get {
                return ResourceManager.GetString("LOG_CHECK_UNICITY_CONSTRAINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete operation failed for {0} with Id {1}..
        /// </summary>
        internal static string LOG_DELETE_OPERATIONFAILED {
            get {
                return ResourceManager.GetString("LOG_DELETE_OPERATIONFAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested {0} not found in the Database. Check database connection..
        /// </summary>
        internal static string LOG_GET_MULTIPLE_NOTFOUND {
            get {
                return ResourceManager.GetString("LOG_GET_MULTIPLE_NOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested {0} not found in the Database.  [info: {1}].
        /// </summary>
        internal static string LOG_GETONE_NOTFOUND {
            get {
                return ResourceManager.GetString("LOG_GETONE_NOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insertion operation of new {0} failed .
        /// </summary>
        internal static string LOG_REGISTER_OPERATIONFAILED {
            get {
                return ResourceManager.GetString("LOG_REGISTER_OPERATIONFAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update {0} operation failed. [info: {1}].
        /// </summary>
        internal static string LOG_UPDATE_OPERATIONFAILED {
            get {
                return ResourceManager.GetString("LOG_UPDATE_OPERATIONFAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update operation failed for {0} property {1} [info: {2}].
        /// </summary>
        internal static string LOG_UPDATE_PROPERTY_OPERATIONFAILED {
            get {
                return ResourceManager.GetString("LOG_UPDATE_PROPERTY_OPERATIONFAILED", resourceCulture);
            }
        }
    }
}
