//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CesiZen.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CesiZen.Domain.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} existe déjà...
        /// </summary>
        internal static string CLIENT_ACCOUNT__UNICITY_CONSTRAINT {
            get {
                return ResourceManager.GetString("CLIENT_ACCOUNT_ UNICITY_CONSTRAINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email ou Mot de passe incorrect..
        /// </summary>
        internal static string CLIENT_AUTHENTICATION_FAILED {
            get {
                return ResourceManager.GetString("CLIENT_AUTHENTICATION_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to échec de suppression : {0}.
        /// </summary>
        internal static string CLIENT_DELETION_FAILED {
            get {
                return ResourceManager.GetString("CLIENT_DELETION_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre déconnection a échoué..
        /// </summary>
        internal static string CLIENT_DISCONNECTION_FAILED {
            get {
                return ResourceManager.GetString("CLIENT_DISCONNECTION_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to échec de la vérification du de l&apos;email.
        /// </summary>
        internal static string CLIENT_EMAIL_VERIFICATION_FAILED {
            get {
                return ResourceManager.GetString("CLIENT_EMAIL_VERIFICATION_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le lien a expiré..
        /// </summary>
        internal static string CLIENT_EXPIRED_LINK {
            get {
                return ResourceManager.GetString("CLIENT_EXPIRED_LINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to échec de la création..
        /// </summary>
        internal static string CLIENT_INSERTION_FAILED {
            get {
                return ResourceManager.GetString("CLIENT_INSERTION_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre compte est bloqué pendant {0} minutes..
        /// </summary>
        internal static string CLIENT_LOCKTIME {
            get {
                return ResourceManager.GetString("CLIENT_LOCKTIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous avez atteint le nombre maximum de tentatives de connexion ! Votre compte est bloqué pendant 5 minutes..
        /// </summary>
        internal static string CLIENT_LOGIN_ATTEMPS_REACHED {
            get {
                return ResourceManager.GetString("CLIENT_LOGIN_ATTEMPS_REACHED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} introuvables..
        /// </summary>
        internal static string CLIENT_MULTIPLE_NOTFOUND {
            get {
                return ResourceManager.GetString("CLIENT_MULTIPLE_NOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} introuvable..
        /// </summary>
        internal static string CLIENT_NOTFOUND {
            get {
                return ResourceManager.GetString("CLIENT_NOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le mot de passe doit correspondre au mot de passe de confirmation..
        /// </summary>
        internal static string CLIENT_PASSWORD_NOTMATCH {
            get {
                return ResourceManager.GetString("CLIENT_PASSWORD_NOTMATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous avez atteint le nombre maximum de tentatives de renouvellement du mot de passe ! Votre compte est bloqué pendant 1 heure..
        /// </summary>
        internal static string CLIENT_RESET_PASSWORD_ATTEMPS_REACHED {
            get {
                return ResourceManager.GetString("CLIENT_RESET_PASSWORD_ATTEMPS_REACHED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to échec de la mise à jour..
        /// </summary>
        internal static string CLIENT_UPDATE_FAILED {
            get {
                return ResourceManager.GetString("CLIENT_UPDATE_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete operation failed for {0} with Id {1}..
        /// </summary>
        internal static string LOG_DELETE_FAILED {
            get {
                return ResourceManager.GetString("LOG_DELETE_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with email: {0} couldn&apos;t be verified..
        /// </summary>
        internal static string LOG_EMAIL_VERIFICATION_FAILED {
            get {
                return ResourceManager.GetString("LOG_EMAIL_VERIFICATION_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested {0} not found in the Database. Check database connection..
        /// </summary>
        internal static string LOG_GET_MULTIPLE_NOTFOUND {
            get {
                return ResourceManager.GetString("LOG_GET_MULTIPLE_NOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested {0} not found in the Database.  [Id: {1}].
        /// </summary>
        internal static string LOG_GETONE_NOTFOUND {
            get {
                return ResourceManager.GetString("LOG_GETONE_NOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t save {0} into Database..
        /// </summary>
        internal static string LOG_INSERTION_OPERATIONFAILED {
            get {
                return ResourceManager.GetString("LOG_INSERTION_OPERATIONFAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  {0} attemps has been made for user account {1}.
        /// </summary>
        internal static string LOG_LOGIN_ATTEMPS_COUNT {
            get {
                return ResourceManager.GetString("LOG_LOGIN_ATTEMPS_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} has reached login limit attemps. Account is locked for 5 minutes..
        /// </summary>
        internal static string LOG_LOGIN_ATTEMPS_REACHED {
            get {
                return ResourceManager.GetString("LOG_LOGIN_ATTEMPS_REACHED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current operation failed : {0}.
        /// </summary>
        internal static string LOG_OPERATIONFAILED {
            get {
                return ResourceManager.GetString("LOG_OPERATIONFAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insertion operation of new user {0} failed. .
        /// </summary>
        internal static string LOG_REGISTER_FAILED {
            get {
                return ResourceManager.GetString("LOG_REGISTER_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} has reached reset password limit attemps. Account locked for 1 hour..
        /// </summary>
        internal static string LOG_RESET_PASSWORD_ATTEMPS_REACHED {
            get {
                return ResourceManager.GetString("LOG_RESET_PASSWORD_ATTEMPS_REACHED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to provided {0} already exist in the Database. [value: {1}].
        /// </summary>
        internal static string LOG_UNICITY_CONSTRAINT {
            get {
                return ResourceManager.GetString("LOG_UNICITY_CONSTRAINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update {0} with Id: {1}.
        /// </summary>
        internal static string LOG_UPDATE_FAILED {
            get {
                return ResourceManager.GetString("LOG_UPDATE_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update {0} {1} property .
        /// </summary>
        internal static string LOG_UPDATE_PROPERTY_FAILED {
            get {
                return ResourceManager.GetString("LOG_UPDATE_PROPERTY_FAILED", resourceCulture);
            }
        }
    }
}
