//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CesiZen.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InfoMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InfoMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CesiZen.Domain.Resources.InfoMessages", typeof(InfoMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le compte a été désactivé..
        /// </summary>
        internal static string CLIENT_ACCOUNT_DISABLED {
            get {
                return ResourceManager.GetString("CLIENT_ACCOUNT_DISABLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le compte a été activé..
        /// </summary>
        internal static string CLIENT_ACCOUNT_ENABLED {
            get {
                return ResourceManager.GetString("CLIENT_ACCOUNT_ENABLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous êtes maintenant connecté !.
        /// </summary>
        internal static string CLIENT_AUTHENTIFIED {
            get {
                return ResourceManager.GetString("CLIENT_AUTHENTIFIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} a été supprimé..
        /// </summary>
        internal static string CLIENT_DELETE_SUCCESS {
            get {
                return ResourceManager.GetString("CLIENT_DELETE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un Email a été envoyé pour la vérification..
        /// </summary>
        internal static string CLIENT_EMAIL_VERIFICATION {
            get {
                return ResourceManager.GetString("CLIENT_EMAIL_VERIFICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre email a été vérifié..
        /// </summary>
        internal static string CLIENT_EMAIL_VERIFIED {
            get {
                return ResourceManager.GetString("CLIENT_EMAIL_VERIFIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} a été créé..
        /// </summary>
        internal static string CLIENT_INSERTION_SUCCESS {
            get {
                return ResourceManager.GetString("CLIENT_INSERTION_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mot de passe modifié..
        /// </summary>
        internal static string CLIENT_RESETPASSWORD_SUCCESS {
            get {
                return ResourceManager.GetString("CLIENT_RESETPASSWORD_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Fermé..
        /// </summary>
        internal static string CLIENT_SESSION_CLOSED {
            get {
                return ResourceManager.GetString("CLIENT_SESSION_CLOSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} a été mis à jour..
        /// </summary>
        internal static string CLIENT_UPDATE_SUCCESS {
            get {
                return ResourceManager.GetString("CLIENT_UPDATE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Account number {0} has been activate..
        /// </summary>
        internal static string LOG_ACCOUNT_ACTIVATED {
            get {
                return ResourceManager.GetString("LOG_ACCOUNT_ACTIVATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Account number {0} has been disactivate..
        /// </summary>
        internal static string LOG_ACCOUNT_DISACTIVATED {
            get {
                return ResourceManager.GetString("LOG_ACCOUNT_DISACTIVATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author : {0}, created new article entitled : {1}.
        /// </summary>
        internal static string LOG_ARTICLE_INSERTION {
            get {
                return ResourceManager.GetString("LOG_ARTICLE_INSERTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} has been authentified.
        /// </summary>
        internal static string LOG_AUTHENTIFIED {
            get {
                return ResourceManager.GetString("LOG_AUTHENTIFIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} has been retrieved..
        /// </summary>
        internal static string LOG_COLLECT_COMPLETED {
            get {
                return ResourceManager.GetString("LOG_COLLECT_COMPLETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been deleted..
        /// </summary>
        internal static string LOG_DELETION_SUCCESS {
            get {
                return ResourceManager.GetString("LOG_DELETION_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification email has been sent to {0}.
        /// </summary>
        internal static string LOG_EMAIL_VERIFICATION {
            get {
                return ResourceManager.GetString("LOG_EMAIL_VERIFICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email {0} has been verified..
        /// </summary>
        internal static string LOG_EMAIL_VERIFIED {
            get {
                return ResourceManager.GetString("LOG_EMAIL_VERIFIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} has been formated..
        /// </summary>
        internal static string LOG_FORMAT_COMPLETED {
            get {
                return ResourceManager.GetString("LOG_FORMAT_COMPLETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New {0} {1} has been registered.
        /// </summary>
        internal static string LOG_INSERT_SUCCESS {
            get {
                return ResourceManager.GetString("LOG_INSERT_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password for account {0} has been modified.
        /// </summary>
        internal static string LOG_PASSWORD_MODIFICATION {
            get {
                return ResourceManager.GetString("LOG_PASSWORD_MODIFICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session for user {0} is closed.
        /// </summary>
        internal static string LOG_SESSION_CLOSED {
            get {
                return ResourceManager.GetString("LOG_SESSION_CLOSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} has been updated..
        /// </summary>
        internal static string LOG_UPDATE_PROPERTY {
            get {
                return ResourceManager.GetString("LOG_UPDATE_PROPERTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been updated..
        /// </summary>
        internal static string LOG_UPDATE_SUCCESS {
            get {
                return ResourceManager.GetString("LOG_UPDATE_SUCCESS", resourceCulture);
            }
        }
    }
}
